services:
  notes-app:
    image: notes-app
    container_name: notes-app
    build:
      context: notes
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_started
      mongo-seed:
        condition: service_completed_successfully
      pg-db:
        condition: service_healthy
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - MONGO
    volumes:
      - type: bind
        source: ./containers_data/notes-data/media/
        target: /media
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_HOST=${PG_HOST}
  
  mongo-seed:
    image: mongo-seed
    container_name: mongo-seed
    build:
      context: mongo-seed
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - MONGO
    depends_on:
      mongo:
        condition: service_started
  
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    volumes:
      - type: bind
        source: ./containers_data/mongo-data/db
        target: /data/db
      - type: bind
        source: ./containers_data/mongo-data/configdb
        target: /data/configdb
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGO
    depends_on:
      mongo:
        condition: service_started

  pg-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./containers_data/pg-data
        target: /var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - MONGO
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  MONGO:
    name: MONGO
