services:
  pg-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./containers_data/pg-data
        target: /var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}